### PR TITLE
feat(pullRequest): Allow to skip and parse pull request header

### PR DESCRIPTION
**Pull request by etremblay**
When merging pull request on GitHub or merge requests on gitlab,
a merge header is added to the commit message. The new pullRequestPattren
option allow to parse this line and use the next line as conventional changelog header.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request
- Commit: 4c82a6812605cbb6c12dd56207f758472d90e58d
  - Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines

---

This message was auto-generated by https://gitcop.com

**Comment by stevemao** [comment]
Have you tried https://github.com/ajoslin/conventional-changelog/blob/master/presets/ember.js to config pull requests?

**Comment by etremblay** [comment]
Mixing the ember.js way to skip pull request headers with angular.js preset parsing functions would definitely works.

I considered doing just that, but without https://github.com/ajoslin/conventional-changelog/pull/114 that lead to a lot of _configuration code_ inside my Gruntfile.js

I manage about 20 git projects using https://github.com/btford/grunt-conventional-changelog and we are migating our processes to use pull request only on the master branch.

**Comment by stevemao** [comment]
That issue will be solved soon.

**Comment by stevemao** [comment]
Maybe we can add support for merge header?

**Comment by etremblay** [comment]
I named the feature _pull request_, but it also support _merge requests_ like GitLab does or simple _git merge_ header.  It's basically configured by a RegExp.

**Comment by stevemao** [comment]
I see, I just don't want to over complicate this.

**Comment by stevemao** [comment]
I think the merge commits are always:

Merge `type` `id` from `source` 

So we don't need a pattern regex for this?

**Comment by etremblay** [comment]
Hi,  

I followed the same pattern you did with headerPattern and revertPattern except I did not set the regex by default because I did not want to break the ember.js pluggin in conventional-changelog.

Regular git merge and GitLab merge requests follow the pattern :

```
Merge branch 'feature/pr-test' into 'master'
```

But GitHub pull request are different : 

```
Merge pull request #55 from etremblay/feature/pr-test
```

**Comment by etremblay** [comment]
I added support for `\r\n` line endings and empty line between _merge header_ and _conventional header_

**Comment by etremblay** [comment]
Awesome, thanks for the merge.

**Pull request closed without merging**
