### PR TITLE
fix(regex): not matching JIRA-123 like references

### PR DESCRIPTION
**Pull request by raido**
Updated getReferencePartsRegex() method regex, to match references like JIRA-123. Includes unit test.

### CODE REVIEW

**Comment by stevemao** [comment]
If you could go ahead and do a PR against https://github.com/ajoslin/conventional-changelog/issues/80 for JIRA this change would look more intuitive for me :)
Also `\w` should be used instead of `.` IMO
Otherwise looks good

**Comment by raido** [comment]
Using \w does not match #MY-PROJECT-123.

**Comment by stevemao** [comment]
something like `(?:\w|-)`? Point is to avoid corner cases by matching as less characters as possible :)

**Comment by GitCop** [comment]
There were the following issues with your Pull Request
- Commit: 54bd4185cbefdba730b84b1e647feb71071e978c
  - Your subject line is longer than 100 characters

Guidelines are available at https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines

---

This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request
- Commit: 54bd4185cbefdba730b84b1e647feb71071e978c
  - Your subject line is longer than 100 characters
- Commit: 17ea381f9d3aae8bf4d673835c89feb32d297681
  - Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines

---

This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request
- Commit: 54bd4185cbefdba730b84b1e647feb71071e978c
  - Your subject line is longer than 100 characters
- Commit: 17ea381f9d3aae8bf4d673835c89feb32d297681
  - Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines

---

This message was auto-generated by https://gitcop.com

**Comment by raido** [comment]
Squashed the commits.

**Pull request closed without merging**
